### ISSUE TITLE
No namespace: selmer.filters error

### ISSUE THREAD

**Issue by aaelony** [wiseman/leaflet-gorilla#1] opened 2015-03-19 23:29 UTC
Looks like a great tool, but I ran lein gorilla, opened up the gorilla worksheet and ran

``` clojure
(use 'com.lemondronor.leaflet-gorilla)
```

and got

```
CompilerException java.lang.Exception: No namespace: selmer.filters, compiling:(selmer/filter_parser.clj:1:1) 
```

Cheers,
Avram

**Comment by wiseman** [comment] 2015-03-19 23:45
That's an odd error, being unable to compile something inside a depdendency.  I cloned a fresh version of this repo and tried to reproduce, but it worked for me without error.

I'm not sure what it could be.  Could you paste the output from `lein deps :tree`?

**Comment by wiseman** [comment] 2015-03-19 23:46
And try `lein test` to see if you get the same error.  I run `lein test` in travis and it runs fine so that might test whether it's something specific to your system.

**Comment by aaelony** [comment] 2015-03-20 00:39
I'm running Leiningen 2.5.0 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM 
Perhaps it is something specific to my system.   I'll check it out a bit further.

Thanks for your help,
Avram

**Comment by wiseman** [comment] 2020-01-15 19:10
Closing because this is verrrry old.

**Closed as completed** 2020-01-15 19:10 UTC
